### ISSUE TITLE
Preflight 400 gets not catched.

### ISSUE THREAD

**Issue by Stefflan00** [lucascosta/facebook-js-ads-sdk#18]
Using the sdk in a JS Frontend i was running in a token issue. So the token of the user was expired.
```
Response for preflight has invalid HTTP status code 400
```

But the Promise could not been catched. There was also no response. 

@lucascosta 
So I'm not that experienced with Bluebird, but is there a way to catch Preflight errors?

**Comment by lucascosta** [comment]
@Stefflan00 I haven't ran into any trouble like that so far. As far as I know preflight requests are used to verify CORS access control by some libraries (I've seen Angular doing it) and should be dealt with by the server. I also don't Bluebird is responsible for this error. since it's job is only to make the AJAX request. I would look on other aspects of your implementation.

**Comment by malmgren** [comment]
@lucascosta I experience this issue as well. An example is when the token you use have been invalidated, e.g. if the user changed password or revoked access for your app to their Facebook data.

By the look of it, it seem like the `XMLHttpRequest.onload` is not triggered if there is an error in the preflight request. Since this is the case then the token has been invalidated (an HTTP error 400 is returned from the preflight by Facebook), the promise is never resolved or rejected and the only error displayed is the on the browser outputs to the console.

I think adding an `XMLHttpRequest.onerror` and reject the promise from there as well might solve this.

**Comment by lucascosta** [comment]
Merged #40
