### ISSUE TITLE
Facebook Ad Image Upload

### ISSUE THREAD

**Issue by talha-asad** [lucascosta/facebook-js-ads-sdk#28]
Facebook ad image upload is not supported partly because this lib also supports browser based http calls for all of its operations, there needs to be a way to disable that for a select few classes particularly like Ad Image, because it needs to be sent in a specific multi/part request which is not possible through the browser AFAIK.

**Comment by j-jackson** [comment]
@talha-asad would this explain why I keeping seeing "Can not read property 'undefined' of undefined" when trying to upload an image? 

I also found this open question on SO that explains the same issue: https://stackoverflow.com/questions/45142233/create-ad-image-on-facebook-with-lucascosta-js-sdk

Have you found a way around this for now?

**Comment by lucascosta** [comment]
Facebook has recently released the official SDK based on this project. Hence this project will no longer be maintained and I strongly recommend that you switch to their library.
https://developers.facebook.com/ads/blog/post/2017/09/12/autogen-node.js-sdk/ https://github.com/facebook/facebook-nodejs-ads-sdk
